spring.datasource.url=jdbc:postgresql://db.rfpdmwlasipsnxaidkbb.supabase.co:6543/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=cunbog-pikcym-1foNxe
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true